SUBREDDITS = {
    'Moescape': 'ideally a balance between awe and awww~.',
    'MoeStash': 'more moe girls.',
    'awwnime': 'all kinds of moe art.',
    'wholesomeyuri': 'a place for yuri lovers.',
    'AnimeBlush': 'blushing anime girls.',
    'Smugs': 'glorious smug anime faces.',
    'Joshi_Kosei': 'SFW Fanart of 2D Girls in High School.',
    'tsunderes': 'well, it\'s tsundere girls.',
    'AnimeLounging': 'pics of people lounging around idly.',
    'animehotbeverages': 'anime characters enjoy hot beverages.',
    'Animewallpaper': 'Anime and anime-style wallpapers.',
    'TwoDeeArt': '2D and anime related art.',
    '2DArtchive': 'more 2D arts.',
    'pantsu': 'fanservicey art from manga, anime, VNs, JRPGs, etc.',
    'Patchuu': 'a place for anime fanart with abstract.',
    'Usagimimi': 'bunniegirls.',
    'kitsunemimi': 'foxgirls.',
    'cutelittlefangs': 'for fans of characters with fangs.',
    'headpats': 'anime characters in need of or receiving headpats.',
    'ChurchofBelly': 'place where appreciate the belly.',
    'animelegs': 'place where appreciate the legs.',
    'ZettaiRyouiki': '("Absolute Territory")',
    'thighdeology': 'more thighs but NSFW.',
    'pouts': 'pouting girls and sometimes guys.',
    'gao': 'cute anime girls making scary noises "gao!".',
    'tyingherhairup': 'anime girls tying their hair up.',
    'twintails': 'anime girls with twintails.',
    'animeponytails': 'for those who have a fetish for ponytails.',
    'silverhair': 'for all silver-haired waifu needs.',
    'longhairedwaifus': 'dedicated to anime girls with long hair.',
    'shorthairedwaifus': 'pictures of anime girls with short hair.',
    'OfficialSenpaiHeat': 'art of cute girls. freedom of Weebs.',
}
