"""First migration

Revision ID: 90af47d11fac
Revises: 
Create Date: 2022-07-25 22:48:55.220854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90af47d11fac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('nsfw_is_ok', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian'), server_default='english', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
